### PR TITLE
Changed the faulty font line

### PR DESCRIPTION
**Pull request by Anupam-dagar**

### CODE REVIEW

**Comment by gauthamzz** [comment]
Could you resolve the merge conflicts

**Comment by Anupam-dagar** [comment]
merge conflicts resolved

**Comment by Anupam-dagar** [comment]
my bad,
team page also got pushed.

**Comment by gauthamzz** [comment]
lol create a branch while you are working on different issues, each issue should be in another branch.

try `git checkout -b branchname` and start working on that branch

**Comment by Anupam-dagar** [comment]
ok doing it sir.

**Pull request closed without merging**
