### PR TITLE
Added team page for the humble fool cup.Issue no.(#7)

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Currently added mentors name in the team section.

### CODE REVIEW

**Comment by gauthamzz** [comment]
Live link ?

**Comment by Anupam-dagar** [comment]
Live link:
https://anupam-dagar.github.io/humblefoolcup/

**Comment by gauthamzz** [comment]
I'm sorry don't keep any of our pics :9 
Please use materializecss header and footer also . We need to maintain consistency in design

**Comment by Anupam-dagar** [comment]
ok going to use materialzecss now.
What pic should I use?

**Comment by magician03** [comment]
@Anupam-dagar , thanks for your contributions, here are few things I have noticed

- for the consistency of design and theme, use materialise
- we are not the team members, just put some dummy pics and lorem ipsum for text
- you might be required to change the color theme once the main site layout has been finalised
- change the background water mark to humblefool cup text, if its an image remove it.
- The site is not responsive for mobile screens, try to improve that part using materialize and media queries
- Mention at the bottom, that site is built by Opencode participants, and put a link to humblefool cup contributors list
- From next time, please pitch in before solving the issue, there are many things need to be informed like the above ones. We donot want to waste your time and work done.

Everything else is fine !!

Cheers,
Diwakar

**Comment by Anupam-dagar** [comment]
I got it.
Working towards it.
Thanx.

**Comment by gauthamzz** [comment]
Any Joe doe image . Nothing just a random image we will add images later

**Pull request closed without merging**
