### PR TITLE
Added Events Section.Issue no.(#9)

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Live link:
https://anupam-dagar.github.io/humblefoolcup/

### CODE REVIEW

**Comment by gauthamzz** [comment]
Could you add it above sponsors

**Comment by Anupam-dagar** [comment]
Done. :+1:

**Comment by Anupam-dagar** [comment]
Is the events section fine now?

**Comment by gauthamzz** [comment]
Yup :+1:

**Pull request merged**
