### PR TITLE
Changes in text-color and some minor typos

### PR DESCRIPTION
**Pull request by himanshub16**
@magician03 Please review them.

### CODE REVIEW

**Comment by gauthamzz** [comment]
Provide live link ?

**Comment by himanshub16** [comment]
Link for?

**Comment by gauthamzz** [comment]
To see the changrs live 
Via enabling gh pages

**Comment by himanshub16** [comment]
This site can be hosted on GitHub. So, not live reloading will be required.

**Comment by magician03** [comment]
@himanshub16 , @gauthamzz , everything looks fine, merging

**Pull request merged**
